import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import List from '@/components/List'
import Map from '@/components/Map'
import PleaceDetail from '@/components/PleaceDetail'
import { Flex } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
         <Flex justifyContent={'center'} alignItems={'center'} width={'100vw'} height={'100vh'} maxWidth={'100vw'} maxHeight={'100vh'} position={'relative'} >
          <Header/>
          <List/>
          <Map/>
         </Flex>
        </div>
      </main>
    </>
  )
}
